spring.application.name=tarefas

#endereço do banco
spring.datasource.url=jdbc:h2:mem:tarefasdb;DB_CLOSE_DELAY=-1

#driver do H2
spring.datasource.driver-class-name=org.h2.Driver

#Usuario e senha
spring.datasource.username=sa
spring.datasource.password=

#Criaçao automatica das tabelas
spring.jpa.hibernate.ddl-auto=update

#Exibir comandos SQL
spring.jpa.show-sql=true

#Formatar os comandos SQL
spring.jpa.properties.hibernate.format_sql=true

#Habilitar console
spring.h2.console.enabled=true

#Endereço do console
spring.h2.console.path=/h2-console
